[WIP]コメント機能
sentral1110728/Qiita pull request #13
Opened 2019-02-07 04:54 UTC by sentral1110728

# What
記事に対してコメントができる機能を実装する
# Why
記事に対する他人の意見や見方を知ることができ、コミュニケーションにもなる

2019-02-10 03:24 UTC, sentral1110728 commented
https://gyazo.com/1e9d7af8358f9079b585bc244b34b993
コメントの動作

2019-02-10 03:28 UTC, TOMARUMARU commented on app/assets/javascripts/comments.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
coffeeファイル使用してなければ消しましょう

2019-02-10 03:28 UTC, TOMARUMARU commented on app/assets/stylesheets/comments.scss
> +// Place all the styles related to the comments controller here.
こちらのファイルも使用してなければ

2019-02-10 03:28 UTC, TOMARUMARU commented on app/controllers/comments_controller.rb
> +    redirect_to article_path(params[:article_id])
redirect_to article_path(@comment.article)とかの方がいいかもです

2019-02-10 03:37 UTC, sentral1110728 commented on app/assets/javascripts/comments.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
削除しました。

2019-02-10 03:37 UTC, sentral1110728 commented on app/assets/stylesheets/comments.scss
> +// Place all the styles related to the comments controller here.
削除しました。

2019-02-10 03:38 UTC, sentral1110728 commented on app/controllers/comments_controller.rb
> +    redirect_to article_path(params[:article_id])
リダイレクト先をアソシエーションで定義しました。

2019-02-10 03:40 UTC, ghost requested changes

2019-02-10 03:40 UTC, hiroki5123 commented on app/controllers/comments_controller.rb
> +    @comment = Comment.create(comment_params)
保存できなかった時の分岐をしましょう

2019-02-11 05:49 UTC, sentral1110728 commented on app/controllers/comments_controller.rb
> +    @comment = Comment.create(comment_params)
分岐を記述しました。

2019-02-11 05:55 UTC, ghost requested changes

2019-02-11 05:55 UTC, hiroki5123 commented on app/controllers/comments_controller.rb
> +      redirect_to articles_path
失敗した時はrenderで読み込みましょう

2019-02-16 06:42 UTC, sentral1110728 commented on app/controllers/comments_controller.rb
> +      redirect_to articles_path
表示したいviewが別のコントローラーなので、そのままredirect_toを使用しています。

2019-02-16 06:46 UTC, TOMARUMARU commented on app/controllers/comments_controller.rb
> +      redirect_to article_path(@comment.article)
これって結局saveできてもできなくてもredirectするってことですよね？
でしたら
```
def create
  @comment = Comment.create(comment_params)
  redirect_to article_path(@comment.article)
end
```
で良さそうです

2019-02-16 06:50 UTC, sentral1110728 commented on app/controllers/comments_controller.rb
> +      redirect_to article_path(@comment.article)
ありがとうございます！
そうさせていただきます！

2019-02-16 06:53 UTC, TOMARUMARU approved these changes
LGTMです。お疲れ様でした

2019-02-16 06:58 UTC, sentral1110728 commented
> LGTMです。お疲れ様でした

ありがとうございました！

2019-02-17 06:50 UTC, merged