[WIP]ログイン後トップページ作成
sentral1110728/Qiita pull request #5
Opened 2019-01-20 08:11 UTC by sentral1110728

# What
ログイン後に表示するトップページを作成する。
# Why
必須機能のため。

2019-01-20 10:52 UTC, ghost requested changes

2019-01-20 10:52 UTC, hiroki5123 commented on app/assets/stylesheets/_header.scss
> +        padding-bottom: 16px;
なんかここpadding指定を3つくらいしてるのでまとめましょう

2019-01-20 10:52 UTC, hiroki5123 commented on app/assets/stylesheets/_header.scss
> +        padding: 0 16px 0 12px;
ここも上でpadding指定しているので、まとめましょう

2019-01-20 11:12 UTC, sentral1110728 commented on app/assets/stylesheets/_header.scss
> +        padding-bottom: 16px;
指摘ありがとうございます。まとめました。

2019-01-20 11:12 UTC, sentral1110728 commented on app/assets/stylesheets/_header.scss
> +        padding: 0 16px 0 12px;
まとめました。

2019-01-20 11:20 UTC, kuroko918 requested changes
残りのaタグも全てlink_toに全て書き換えておきましょう！

2019-01-20 11:20 UTC, kuroko918 commented on app/views/devise/sessions/new.html.haml
> +              %a{href: '/'}
link_toに書き換えておきましょう！

2019-01-20 11:20 UTC, kuroko918 commented on app/views/shared/_header.html.haml
> +        %img{src: ""}
image_tagに書き換えておきましょう！

2019-01-21 01:52 UTC, sentral1110728 commented on app/views/devise/sessions/new.html.haml
> +              %a{href: '/'}
ご指摘ありがとうございます。link_toに書き換えました。

2019-01-21 01:52 UTC, sentral1110728 commented on app/views/shared/_header.html.haml
> +        %img{src: ""}
image_tagに書き換えました。

2019-01-21 02:04 UTC, miyagit approved these changes
LGTMです。

2019-01-21 02:41 UTC, sentral1110728 commented
ありがとうございます。

2019-01-21 02:42 UTC, merged