[WIP]記事投稿機能
sentral1110728/Qiita pull request #7
Opened 2019-01-21 07:55 UTC by sentral1110728

# What
記事を投稿し、保存するための機能を実装する。
# Why
記事を投稿・保存し、その記事を共有したいため。

2019-01-28 01:56 UTC, miyagit reviewed
コメントしました。

2019-01-28 01:56 UTC, miyagit commented on app/views/shared/_main-contents.html.haml
> +        - @articles.each do |article|
部分テンプレートを使いましょう！

2019-01-28 02:09 UTC, takebn26 requested changes

2019-01-28 02:09 UTC, takebn26 commented on app/controllers/articles_controller.rb
> +    @articles = Article.order("created_at DESC")
`order(created_at: :desc)`
を使っていきましょう

2019-01-28 02:09 UTC, takebn26 commented on app/controllers/articles_controller.rb
> +    Article.create(article_params)
成功時失敗時の判定はmustで入れましょう

2019-01-28 02:09 UTC, takebn26 commented on app/views/shared/_article.html.haml
> +    = link_to root_path, class: 'article__item__body__meta' do
こちらに二つ並んでいるlinkは現在はどちらもroot_pathで合っているのでしょうか？

2019-01-28 05:43 UTC, sentral1110728 commented on app/controllers/articles_controller.rb
> +    @articles = Article.order("created_at DESC")
使用しました。

2019-01-28 08:03 UTC, sentral1110728 commented on app/views/shared/_article.html.haml
> +    = link_to root_path, class: 'article__item__body__meta' do
まだshowアクションを定義していないのでpathがないのですが、作成しておいたほうがいいんですか？
ちなみに、showアクションはあとで定義しようと思っていました。

2019-01-30 02:54 UTC, sentral1110728 commented on app/views/shared/_main-contents.html.haml
> +        - @articles.each do |article|
使用しました。

2019-01-30 03:25 UTC, sentral1110728 commented on app/controllers/articles_controller.rb
> +    Article.create(article_params)
条件分岐を使用しました。

2019-01-30 03:29 UTC, miyagit approved these changes
LGTMdせう。

2019-01-30 03:31 UTC, sentral1110728 commented
> LGTMdせう。

ありがとうございます！

2019-01-30 03:52 UTC, merged